[[headers]]
for = "/*"

[headers.values]
  Content-Security-Policy = "default-src 'self'; 
  base-uri 'none'; 
  form-action 'none'; 
  frame-ancestors 'self'; 
  img-src 'self'; 
  media-src 'self'; 
  object-src 'none'; 
  script-src 'self' 'unsafe-inline'; 
  style-src 'self'; 
  script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https://platform.twitter.com/widgets.js; 
  font-src 'self' data:;"
          Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=15768000"
   X-Content-Type-Options = "nosniff"
          X-Frame-Options = "DENY"
         X-XSS-Protection = "1; mode=block"