[[headers]]
for = "/*"

[headers.values]
  Content-Security-Policy = "default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; img-src 'self'; media-src 'self'; object-src 'none'; font-src-elem 'self' https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0; script-src-elem 'sha256-xB8KQ9znB/xULMtsjr37zpV3M7JR/XSq1HT6tWKn+G8='  https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v11.0 https://platform.linkedin.com/in.js https://www.googletagmanager.com/gtag/js?id=G-70K0QDFJZW; style-src-elem 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='  https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css; frame-src 'self'"
          Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=15768000"
   X-Content-Type-Options = "nosniff"
          X-Frame-Options = "DENY"
         X-XSS-Protection = "1; mode=block"